# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DarbyCAT
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Explore computers and technology with your peers at Darby High School.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://darbycat.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
fenced_code_blocks: true
kramdown:
    input: GFM
    fenced_code_blocks: true
